### ISSUE TITLE
[MANTRUN-19] Cannot use maven ant tasks in antrun

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#120]
**[Mark Hobson](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mihobson)** opened **[MANTRUN-19](https://issues.apache.org/jira/browse/MANTRUN-19?redirect=false)** and commented

In an attempt to subvert MNG-896 I'm using the maven ant tasks within antrun (see attached testcase).  This leads to the following error, presumably due to the multiple plexus configuration files:

[INFO] ----------------------------------------------------------------------------
[INFO] Building test:test:war:1.0
[INFO]    task-segment: [package]
[INFO] ----------------------------------------------------------------------------
[INFO] [resources:resources]
[INFO] [antrun:run {execution: default}]
[INFO] Executing tasks

process-resources:
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Diagnosis: Error executing ant tasks
[INFO] ----------------------------------------------------------------------------
[ERROR] Cause:
org.apache.maven.plugin.MojoExecutionException: Error executing ant tasks
at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:62)
at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:63)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:357)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:479)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:452)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:438)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:131)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:186)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:302)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: The following error occurred while executing this line: C:\Documents and Settings\mark\Desktop\test\build.xml:13: Unable to start embedder
at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:539)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:384)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)
at org.apache.tools.ant.Task.perform(Task.java:364)
at org.apache.tools.ant.Target.execute(Target.java:341)
at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:56)
... 17 more
Caused by: C:\Documents and Settings\mark\Desktop\test\build.xml:13: Unable to start embedder
at org.apache.maven.artifact.ant.AbstractArtifactTask.getEmbedder(AbstractArtifactTask.java:323)
at org.apache.maven.artifact.ant.AbstractArtifactTask.lookup(AbstractArtifactTask.java:284)
at org.apache.maven.artifact.ant.AbstractArtifactTask.createLocalArtifactRepository(AbstractArtifactTask.java:77)
at org.apache.maven.artifact.ant.DependenciesTask.execute(DependenciesTask.java:73)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)
at org.apache.tools.ant.Task.perform(Task.java:364)
at org.apache.tools.ant.Target.execute(Target.java:341)
at org.apache.tools.ant.Target.performTasks(Target.java:369)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1216)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:37)
at org.apache.tools.ant.Project.executeTargets(Project.java:1068)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:382)
... 21 more
Caused by: org.codehaus.plexus.PlexusContainerException: Error starting container
at org.codehaus.plexus.DefaultPlexusContainer.start(DefaultPlexusContainer.java:766)
at org.codehaus.plexus.embed.Embedder.start(Embedder.java:208)
at org.codehaus.plexus.embed.Embedder.start(Embedder.java:171)
at org.apache.maven.artifact.ant.AbstractArtifactTask.getEmbedder(AbstractArtifactTask.java:319)
... 32 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentRepositoryException: Component descriptor role: 'org.apache.maven.artifact.repository.metadata.RepositoryMetadataManager', implementation: 'org.apache.maven.artifact.repository.metadata.DefaultRepositoryMetadataManager', role hint: 'default' has a hint, but there are other implementations that don't
at org.codehaus.plexus.component.repository.DefaultComponentRepository.addComponentDescriptor(DefaultComponentRepository.java:184)
at org.codehaus.plexus.DefaultPlexusContainer.addComponentDescriptor(DefaultPlexusContainer.java:492)
at org.codehaus.plexus.DefaultPlexusContainer.discoverComponents(DefaultPlexusContainer.java:709)
at org.codehaus.plexus.DefaultPlexusContainer.start(DefaultPlexusContainer.java:750)
... 35 more

---

**Attachments:**
- [test.zip](https://issues.apache.org/jira/secure/attachment/12713621/test.zip) (_1.19 kB_)

1 votes, 0 watchers

**Comment by jira-importer** [comment]
**[Jason Reilly](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jdr0887)** commented

I was having the same problem on Windoze w/ Cygwin (2.0.1-SNAPSHOT).  I grabbed the code and changed the META-INF/plexus/components.xml to use the DefaultWagonManager instead of the CustomWagonManager.  I also commented out the CustomWagonManager class casting inside AbstractArtifactTask.createLocalArtifactRepository().

With these two changes running ant scripts works for me.....which is nice.
