### ISSUE TITLE
[MANTRUN-63] ant classpath resolves incorrectly if project is invoked as part of multi-project builds

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#137]
**[Binyan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=binyan)** opened **[MANTRUN-63](https://issues.apache.org/jira/browse/MANTRUN-63?redirect=false)** and commented

I have the following pom definition:

    <plugin>
      <artifactId>maven-antrun-plugin</artifactId>
      <executions>
        <execution>
          <phase>package</phase>
          <configuration>
            <tasks>
              <property name="mpc" refid="maven.plugin.classpath"/>
              <echo>MPC: ${mpc}</echo>
              <ant antfile="build.xml" inheritRefs="true" target="build-installer"/>
            </tasks>
          </configuration>
          <goals>
            <goal>run</goal>
          </goals>
        </execution>
      </executions>
      <dependencies>
        <dependency>
          <groupId>ant</groupId>
          <artifactId>ant-nodeps</artifactId>
          <version>1.6.5</version>
        </dependency>
      </dependencies>
    </plugin>

with the output being:

    [INFO] Executing tasks
    [echo] MPC: C:\Documents and Settings\binyan\.m2\repository\ant\ant-nodeps\1.6.5\ant-nodeps-1.6.5.jar;C:\Documents and Settings\binyan\.m2\repository\ant\ant\1.6.5\ant-1.6.5.jar;C:\Documents and Settings\binyan\.m2\repository\ant\ant-launcher\1.6.5\ant-launcher-1.6.5.jar;E:\maven\lib\maven-project-2.0.4.jar;E:\maven\lib\maven-plugin-api-2.0.4.jar

... [ sucessful build performed] ...

Everything works fine if I build the project standalone, however, if the project is part of a maven multi-project build and invoked by the top level project then I get the following output:

[INFO] Executing tasks
[echo] MPC: C:\Documents and Settings\binyan\.m2\repository\ant\ant\1.6.5\ant-1.6.5.jar;C:\Documents and Settings\binyan\.m2\repository\ant\ant-launcher\1.6.5\ant-launcher-1.6.5.jar;E:\maven\lib\maven-project-2.0.4.jar;E:\maven\lib\maven-plugin-api-2.0.4.jar

init:
[mkdir] Created dir: E:\dev\workspace-eclipse\MX\installs\target\installer-staging\mxscripts
[mkdir] Created dir: E:\dev\workspace-eclipse\MX\installs\target\installer-staging\wars

build-staging:
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error executing ant tasks

Embedded error: The following error occurred while executing this line:
E:\dev\workspace-eclipse\MX\installs\build.xml:23: Could not create type regexpmapper due to No supported regular expression matcher found
[INFO] ------------------------------------------------------------------------
[INFO] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error executing ant tasks
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:559)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error executing ant tasks
at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:114)
at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:83)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:412)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 16 more
Caused by: The following error occurred while executing this line:
E:\dev\workspace-eclipse\MX\installs\build.xml:23: Could not create type regexpmapper due to No supported regular expression matcher found
at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:539)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:384)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)
at org.apache.tools.ant.Task.perform(Task.java:364)
at org.apache.tools.ant.Target.execute(Target.java:341)
at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:108)
... 19 more
Caused by: E:\dev\workspace-eclipse\MX\installs\build.xml:23: Could not create type regexpmapper due to No supported regular expression matcher found
at org.apache.tools.ant.AntTypeDefinition.createAndSet(AntTypeDefinition.java:281)
at org.apache.tools.ant.AntTypeDefinition.icreate(AntTypeDefinition.java:196)
at org.apache.tools.ant.AntTypeDefinition.create(AntTypeDefinition.java:183)
at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:199)
at org.apache.tools.ant.IntrospectionHelper.createAddTypeCreator(IntrospectionHelper.java:1404)
at org.apache.tools.ant.IntrospectionHelper.getNestedCreator(IntrospectionHelper.java:485)
at org.apache.tools.ant.IntrospectionHelper.getElementCreator(IntrospectionHelper.java:583)
at org.apache.tools.ant.UnknownElement.handleChild(UnknownElement.java:545)
at org.apache.tools.ant.UnknownElement.handleChildren(UnknownElement.java:326)
at org.apache.tools.ant.UnknownElement.configure(UnknownElement.java:182)
at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:158)
at org.apache.tools.ant.Task.perform(Task.java:363)
at org.apache.tools.ant.Target.execute(Target.java:341)
at org.apache.tools.ant.Target.performTasks(Target.java:369)
at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1216)
at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:37)
at org.apache.tools.ant.Project.executeTargets(Project.java:1068)
at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:382)
... 23 more
Caused by: No supported regular expression matcher found
at org.apache.tools.ant.util.regexp.RegexpMatcherFactory.newRegexpMatcher(RegexpMatcherFactory.java:91)
at org.apache.tools.ant.util.regexp.RegexpMatcherFactory.newRegexpMatcher(RegexpMatcherFactory.java:45)
at org.apache.tools.ant.util.RegexpPatternMapper.\<init>(RegexpPatternMapper.java:40)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
at java.lang.reflect.Constructor.newInstance(Constructor.java:494)
at org.apache.tools.ant.AntTypeDefinition.createAndSet(AntTypeDefinition.java:273)
... 40 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 3 seconds
[INFO] Finished at: Tue Nov 21 17:10:01 CST 2006
[INFO] Final Memory: 7M/19M
[INFO] --------------------------------------------------------------------

---

**Affects:** 1.1

**Issue Links:**
- [MANTRUN-51](https://issues.apache.org/jira/browse/MANTRUN-51) Problems with multiple antrun declarations in multiproject
 (_**"duplicates"**_)
- [MNG-1323](https://issues.apache.org/jira/browse/MNG-1323) Plugin extensions (dependencies) not resolved in reactor build
 (_**"duplicates"**_)

13 votes, 7 watchers

**Comment by jira-importer** [comment]
**[Filippos Slavik](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=corfian)** commented

Well, I have the same problem and I finally have an explanation. The problem occurs in a multi-module projects where the antrun plugin is being used in more than one module.

In my case, let's say that my multi-module project has modules A and B. Both modules are using the antrun plugin, but only module B specifies an additional  classpath  for the antrun plugin. If I invoke the antrun plugin within module B everything works great but if I do that  from the parent, then my build fails. This is because module A run it's build cycle before B and for some reason the maven.plugin.classpath was not altered for the antrun plugin when running module B build  (perhaps because it was already defined from module A).

Thanks

**Comment by jira-importer** [comment]
**[denny](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=josephd)** commented

We had exactly the same problem as Filippos -- mutli-module project with the parent (A) and a child (B) both defining an antrun plugin but B's defn having additional dependencies (ant-contrib, etc).  When running mvn from A we get a failure in B.   
Workaround :  Define all your dependencies that you need in the B pom in the A pom.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

See MANTRUN-51
