### ISSUE TITLE
[MANTRUN-111] Error related to running XSLT - v 1.3

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#154]
**[Jethrik](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jethrik)** opened **[MANTRUN-111](https://issues.apache.org/jira/browse/MANTRUN-111?redirect=false)** and commented

The best thing for me to do is probably just try using one of the Maven XSLT plugins, which is what I'll do next, but I figured I'd report this.  My POM looks like this:

    <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-antrun-plugin</artifactId>
         <version>1.3</version>
         <executions>
              <execution>
                       <id>generate-custom-pom</id>
                       <phase>pre-integration-test</phase>
                       <goals>
                                <goal>run</goal>
                       </goals>
                                                                                                                                                                               <configuration>						
                                <tasks>
                                         <xslt in="${basedir}/pom.xml" out="${basedir}/target/pom.xml" style="${basedir}/src/strip-pom-parent.xslt" />
                                                                                                                                                </tasks>						
                       </configuration>
              </execution>
         </executions>
    </plugin>

And running it generates this error:

[INFO] [antrun:run {execution: generate-custom-pom}]
[INFO] Executing tasks
java.lang.ClassNotFoundException: org.apache.tools.ant.taskdefs.optional.TraXLia ison
at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
at org.codehaus.classworlds.RealmClassLoader.loadClassDirect(RealmClassL oader.java:195)
at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassReal m.java:255)
at org.codehaus.classworlds.DefaultClassRealm.loadClass(DefaultClassReal m.java:274)
at org.codehaus.classworlds.RealmClassLoader.loadClass(RealmClassLoader. java:214)
at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:169)
at org.apache.tools.ant.taskdefs.XSLTProcess.loadClass(XSLTProcess.java: 548)
at org.apache.tools.ant.taskdefs.XSLTProcess.resolveProcessor(XSLTProces s.java:533)
at org.apache.tools.ant.taskdefs.XSLTProcess.getLiaison(XSLTProcess.java :785)
at org.apache.tools.ant.taskdefs.XSLTProcess.execute(XSLTProcess.java:30 0)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl. java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.jav a:106)
at org.apache.tools.ant.Task.perform(Task.java:348)
at org.apache.tools.ant.Target.execute(Target.java:357)
at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractA ntMojo.java:118)
at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:98)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPlugi nManager.java:483)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(Defa ultLifecycleExecutor.java:678)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLi fecycle(DefaultLifecycleExecutor.java:540)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(Defau ltLifecycleExecutor.java:519)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHan dleFailures(DefaultLifecycleExecutor.java:371)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegmen ts(DefaultLifecycleExecutor.java:332)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLi fecycleExecutor.java:181)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:356)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:137)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:356)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl. java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces sorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

---

**Affects:** 1.3

**Comment by jira-importer** [comment]
**[Markelov Ruslan](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=balmaster)** commented

you need add dependency to ant-trax in your plugin configuration

something as

    		<plugin>
    			<artifactId>maven-antrun-plugin</artifactId>
    			<executions>
    				<execution>
    					<phase>generate-sources</phase>
    					<configuration>
    						<tasks>
    							<xslt style="..."                                                             ...
    							</xslt>
    
    						</tasks>
    					</configuration>
    					<goals>
    						<goal>run</goal>
    					</goals>
    				</execution>
    
    			</executions>
    			<dependencies>
    				<dependency>
    					<groupId>org.apache.ant</groupId>
    					<artifactId>ant-trax</artifactId>
    					<version>1.7.1</version>
    				</dependency>
    			</dependencies>
    		</plugin>

additional ant dependencies you can find in $ANT_HOME/lib
see pom files

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

You tried to use an ant task that is not part of the set of tasks that are included by default in the antrun plugin. You would have needed to add more dependencies to the plugin.
