### ISSUE TITLE
[MANTRUN-165] Error when executing ANT Task 

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#170]
**[daivish shah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daivish)** opened **[MANTRUN-165](https://issues.apache.org/jira/browse/MANTRUN-165?redirect=false)** and commented

Hi,

I am getting following ERROR while using this configuration.

MAVEN apache-maven-2.2.1 JAVA_HOME - jdk1.5.0_22
I want to compile my classes with Java 1.4.2_04 version
I am using maven-antrun-plugin \<version>1.6\</version>

Please take a look at 2 POM.XML one is PARENT pom.xml  (WorkCenterPlatformMavenProject) and second pom.xml (WPSEjb)

Guide me where i am wrong in setting up the things ? I am really stuck to execute my ANT task.

[FATAL ERROR] Container realm = plexus.core
urls[0] = file:/C:/apache-maven-2.2.1/lib/maven-2.2.1-uber.jar
[INFO] ------------------------------------------------------------------------
[ERROR] FATAL ERROR
[INFO] ------------------------------------------------------------------------
[INFO] org.apache.tools.ant.launch.Locator.fromJarURI(Ljava/lang/String;)Ljava/lang/String;
[INFO] ------------------------------------------------------------------------
[INFO] Trace
java.lang.NoSuchMethodError: org.apache.tools.ant.launch.Locator.fromJarURI(Ljava/lang/String;)Ljava/lang/String;
at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:274)
at org.apache.tools.ant.helper.ProjectHelper2.parseUnknownElement(ProjectHelper2.java:130)
at org.apache.tools.ant.helper.ProjectHelper2.parseAntlibDescriptor(ProjectHelper2.java:110)
at org.apache.tools.ant.taskdefs.Antlib.createAntlib(Antlib.java:91)
at org.apache.tools.ant.taskdefs.Definer.loadAntlib(Definer.java:440)
at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:292)
at org.apache.maven.plugin.antrun.AntRunMojo.initMavenTasks(AntRunMojo.java:449)
at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:259)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:592)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Tue Aug 09 10:16:35 PDT 2011
[INFO] Final Memory: 10M/19M
[INFO] --------------------------------------------------------------------

---

**Attachments:**
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12713667/pom.xml) (_714 bytes_)
- [pom.xml](https://issues.apache.org/jira/secure/attachment/12713685/pom.xml) (_5.78 kB_)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

The version of Antrun Plugin that you are using, uses Ant 1.8.1 underneath. When you add Ant 1.6.5 to the class path, my guess is that the there is some kind of conflict between the two.

**Comment by jira-importer** [comment]
**[daivish shah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daivish)** commented

Yes you are right it's loading 1.8.1 antrun i changed that..

And my details are as below now.

    	<plugin>
    	  <groupId>org.apache.maven.plugins</groupId>	
          <artifactId>maven-antrun-plugin</artifactId>
          <version>1.6</version>
          <executions>
             <execution>
              <id>install</id>
              <phase>install</phase>
               <goals>
              <goal>run</goal>
              </goals>
              <configuration>
              <source>${java-version}</source>
              <target>${java-version}</target>
              <target>
              <property environment="env" />
    		  <property name="weblogic.home" value="${env.WL_HOME}"/>
    		  
    		  <echo message="compile classpath: ${weblogic.home}"/>
    		  
              </target>
              <project name="WLW build" default="build">
    
               <tasks>
    	          <taskdef name="wlwBuild" classname="workshop.core.WlwBuildTask">
              		<classpath refid="maven.dependency.classpath"/>
    
                  <classpath>
                  	  <fileset dir="C:\bea\weblogic81\workshop">
                     	<include name="wlw-ide.jar"/>
                      </fileset>
            	  </classpath>
            	   </taskdef>
            	 <target name="build">
    			<wlwBuild work="C:\TFS\HPRA\Source\Services\WorkCenterPlatform\Java\WorkCenterPlatform\WorkCenterPlatform.work" serverclasspath="${server.classpath}"  classpathref="maven.plugin.classpath"  >
       				<build outputdir="C:\CARR" outputfilename="WPSSchemas.jar" project="WPSSchemas"/>
    			</wlwBuild>
    			</target>
         		</tasks>
              </project>
              </configuration>
             </execution>
           </executions>
    	<dependencies>
     
    	</dependencies>           
    	</plugin>

With this details i am getting following exception.

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] [jar:jar {execution: default-jar}]
[INFO] Building jar: C:\Documents and Settings\DS100193\workspace\WorkCenterPlatformMavenProject\WPSSchemas\target\WPSSchemas-1.0.jar
[INFO] [install:install {execution: default-install}]
[INFO] Installing C:\Documents and Settings\DS100193\workspace\WorkCenterPlatformMavenProject\WPSSchemas\target\WPSSchemas-1.0.jar to C:\Documents and Settings\DS100193\.m2\repository\WPSSchemas\WPSSchemas\1.0\WPSSchemas-1.0.jar
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error configuring: org.apache.maven.plugins:maven-antrun-plugin. Reason: ERROR: Cannot override read-only parameter: project in goal: antrun:run
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2 seconds
[INFO] Finished at: Tue Aug 09 12:20:54 PDT 2011
[INFO] Final Memory: 11M/22M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

"Cannot override read-only parameter: project"

The parameter "project" is read-only, so you cannot use it in your POM. Without reading the source I imagine that it is populated with the current project, so you don't need to use it.

**Comment by jira-importer** [comment]
**[daivish shah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daivish)** commented

Thanks Dennis, Yes i removed the \<project>\</project> Tag from my POM.XML

Then i am getting following error.

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An Ant BuildException has occured: No Project specified

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Tue Aug 09 13:43:32 PDT 2011
[INFO] Final Memory: 12M/21M
[INFO] ------------------------------------------------------------------------

**Comment by jira-importer** [comment]
**[daivish shah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daivish)** commented

I am going to post new Request as i now i moved to other work around.. Means now i am trying to use \<ant antfile="build.xml" /> where i am getting some different errors.

**Comment by jira-importer** [comment]
**[daivish shah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daivish)** commented

Trying to use other workaround.
