### ISSUE TITLE
[MANTRUN-220] java.lang.UnsupportedClassVersionError: Bad version number in .class file

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#195]
**[mengln](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mengln)** opened **[MANTRUN-220](https://issues.apache.org/jira/browse/MANTRUN-220?redirect=false)** and commented

```xml
<plugin>
 <artifactId>maven-antrun-plugin</artifactId>
 <executions>
 <execution>
 <id>install with JDK5</id>
 <phase>install</phase>
 <configuration>
 <tasks>
 <exec executable="${basedir}/mvn_jdk5.bat" output="log.txt" failonerror="true">
 <arg value="install"/>
 <arg value="..
 a-geronimo"/>
 </exec>
 </tasks>
 </configuration>
 <goals>
 <goal>run</goal>
 </goals>
 </execution>
 <execution>
 <id>clean with JDK5</id>
 <phase>clean</phase>
 <configuration>
 <tasks>
 <exec executable="${basedir}/mvn_jdk5.bat" output="log.txt" failonerror="true">
 <arg value="clean"/>
 <arg value="..
 a-geronimo"/>
 </exec>
 </tasks>
 </configuration>
 <goals>
 <goal>run</goal>
 </goals>
 </execution>
 </executions>
 </plugin>
```

 

```
if "%JAVA5_HOME%" == "" (
 echo "ERROR:Please Set JAVA5_HOME"
 exit /b 1
 )
 Set JAVA_HOME=%JAVA5_HOME%
 Set MVN_GOAL=%1


 if "%2" neq "" (
 Set WORK_DIR=%2 
 ) else (
 Set WORK_DIR=.\ 
 )
 cd %WORK_DIR%

REM [maven ]
 echo JAVA_HOME : "%JAVA_HOME%"
 echo Work Directory : "%WORK_DIR%"
 echo Command : mvn %MVN_GOAL%

call mvn.cmd %MVN_GOAL%

echo ErrorLevel:%ERRORLEVEL%

if ERRORLEVEL 1 (
 exit /b %ERRORLEVEL%

)
```

Previously used is java6+maven2.2.1, you need to make some projects compile with java5, compile without problems. Now need to change the version of java, use java11+maven3.6.0, compile problems, query maven3.6.0 support java1.7 and above, but change java_home to 1.7 will give an error: Java heap space.

Error message:

```
JAVA_HOME : "G:\buildtool\jdk1.5.0_18"
 Work Directory : "..
 a-geronimo "
 Command : mvn clean
 java.lang.UnsupportedClassVersionError: Bad version number in .class file
 at java.lang.ClassLoader.defineClass1(Native Method)
 at java.lang.ClassLoader.defineClass(ClassLoader.java:620)
 at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:124)
 at java.net.URLClassLoader.defineClass(URLClassLoader.java:260)
 at java.net.URLClassLoader.access$100(URLClassLoader.java:56)
 at java.net.URLClassLoader$1.run(URLClassLoader.java:195)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:268)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:251)
 at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:319)
 Exception in thread "main" ErrorLevel:1
```

 

---

**Affects:** 1.8

**Comment by jira-importer** [comment]
**[Michael Osipov](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=michael-o)** commented

I do not understand the problem.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

The problem is in mvn_jdk5.bat : Maven 3.6.2 requires at least Java 7 to run with.
I don't see any specific things here that requires ant, so I'd suggest to drop the maven-antrun-plugin and switch to dedicated maven-plugins.
