### ISSUE TITLE
[MANTRUN-37] Antrun breaks when using xdoclet plugin

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#207]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** opened **[MANTRUN-37](https://issues.apache.org/jira/browse/MANTRUN-37?redirect=false)** and commented

I just updated to antrun v1.1 (which needs to be marked as released in jira BTW) and find that my multimodule build is now breaking.  Running the build in the child module itself works fine but if I build the parent, it fails when it gets to the child with the antrun task.  Here's part of the debug output.  Note it says 1.1 in the dependency tree but 1.0 further down.

```
[DEBUG] org.apache.maven.plugins:maven-antrun-plugin:maven-plugin:1.1 (selected for runtime)
[DEBUG]   org.apache.maven:maven-project:jar:2.0.1 (selected for runtime)
[DEBUG]     org.apache.maven:maven-model:jar:2.0.1 (selected for runtime)
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.0.5 (selected for runtime)
[DEBUG]         classworlds:classworlds:jar:1.1-alpha-2 (selected for runtime)
[DEBUG]     org.apache.maven:maven-profile:jar:2.0.1 (selected for runtime)
[DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9 (selected for runtime)
[DEBUG]         org.codehaus.plexus:plexus-utils:jar:1.0.4 (removed - nearer found: 1.0.5)
[DEBUG]         junit:junit:jar:3.8.1 (selected for runtime)
[DEBUG]     org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9 (selected for runtime)
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:1.0.4 (removed - nearer found: 1.0.5)
[DEBUG]       classworlds:classworlds:jar:1.1-alpha-2 (selected for runtime)
[DEBUG]       junit:junit:jar:3.8.1 (selected for runtime)
[DEBUG]     org.codehaus.plexus:plexus-utils:jar:1.0.5 (selected for runtime)
[DEBUG]     org.apache.maven:maven-artifact-manager:jar:2.0.1 (selected for runtime)
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:2.0.1 (selected for runtime)
[DEBUG]       org.apache.maven.wagon:wagon-provider-api:jar:1.0-alpha-5 (selected for runtime)
[DEBUG]         org.codehaus.plexus:plexus-utils:jar:1.0.4 (removed - nearer found: 1.0.5)
[DEBUG]       org.apache.maven:maven-artifact:jar:2.0.1 (selected for runtime)
[DEBUG]     org.apache.maven:maven-artifact:jar:2.0.1 (selected for runtime)
[DEBUG]   org.apache.maven:maven-plugin-api:jar:2.0.1 (selected for runtime)
[DEBUG]   ant:ant:jar:1.6.5 (selected for runtime)
[DEBUG]   ant:ant-launcher:jar:1.6.5 (selected for runtime)
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run': Unable to find the mojo 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run' in the plugin 'org.apache.maven.plugins:maven-antrun-plugin'
Component descriptor cannot be found in the component repository: org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-antrun-plugin:1.0:run.
[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run': Unable to find the mojo 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run' in the plugin 'org.apache.maven.plugins:maven-antrun-plugin'
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:472)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:451)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:303)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:270)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:139)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:324)
	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run' in the plugin 'org.apache.maven.plugins:maven-antrun-plugin'
	at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:553)
	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:410)
	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:530)
	... 16 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository: org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-antrun-plugin:1.0:run.
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:312)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
	at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:544)
	... 18 more
```

My POM has this in the build plugins:

```
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-antrun-plugin</artifactId>
<version>1.1</version>
```

---

**Affects:** 1.1

**Issue Links:**
- [MANTRUN-49](https://issues.apache.org/jira/browse/MANTRUN-49) \<taskdef/> seems ignoring classpath

16 votes, 14 watchers

**Comment by jira-importer** [comment]
**[Fredrik Vraalsen](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=fredriv)** commented

I'm also seeing this problem with maven 2.0.4 and antrun 1.1 in a multiproject build. Environment is JDK 1.5.0_06, Windows XP.
The submodule build crashes with the same type of error message as in the original bug description.  The build works however if I explicitly specify version 1.0 of the antrun in the plugin in the pom, as Mike Pernham pointed out in one of his comments.

I've tried disabling various subprojects and plugins, and I've finally hit a case where I can trigger the error by enabling a single plugin: The culprit seems to be the xdoclet plugin from mojo.codehaus.org.  When this is enabled in one of the other subprojects, the antrun 1.1 plugin fails, otherwise it runs fine.

I've created a testcase which can be checked out using

svn co https://svn.sourceforge.net/svnroot/coras/coras/branches/maven2-antrun-testcase/src

The module with the antrun problem is in modules/coras-help.  The module using xdoclet is in modules/asset-repository-ejb.  Sorry I haven't had a chance to create an even smaller testcase, but I figured it would be worth getting this out there.  Don't know if the problem is with the antrun or the xdoclet plugin though.

**Comment by jira-importer** [comment]
**[David Smiley](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dsmiley)** commented

I am also seeing this very same problem.  Specifying v1.0 does remove the bug.  I also am using xdoclet, as Frederik is too.  Please reopen this bug.

**Comment by jira-importer** [comment]
**[Carlos Sanchez Gonzalez](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=carlos)** commented

Reopen per user comment

**Comment by jira-importer** [comment]
**[Martin Heitz](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mattin)** commented

Having the same problem.
Seems to be related to the use of xdoclet, which is loading antrun 1.0...

Extract from pom:
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-antrun-plugin\</artifactId>
\<version>1.1\</version>
\<executions>
...

Stack trace (which shows, that 1.0 is used, although 1.1 is configured) follows:
INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run': Unable to find the mojo 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run' in the plugin 'org.apache.maven.plugins:maven-antrun-plugin'
Component descriptor cannot be found in the component repository: org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-antrun-plugin:1.0:run.
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run': Unable to find the mojo 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run' in the plugin 'org.apache.maven.plugins:maven-antrun-plugin'
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:538)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:475)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:454)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:306)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:273)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:140)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:322)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:115)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:256)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:324)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.PluginManagerException: Unable to find the mojo 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run' in the plugin 'org.apache.maven.plugins:maven-antrun-plugin'
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:533)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:390)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:534)
... 16 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: Component descriptor cannot be found in the component repository: org.apache.maven.plugin.Mojoorg.apache.maven.plugins:maven-antrun-plugin:1.0:run.
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:323)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:312)
at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:440)
at org.apache.maven.plugin.DefaultPluginManager.getConfiguredMojo(DefaultPluginManager.java:524)
... 18 more

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

This definitely has to do with the xdoclet plugin using antrun 1.0 directly and then the build later trying to use antrun 1.1.  I'd suggest releasing a new version of xdoclet plugin which uses antrun 1.1.  Hopefully sync'ing the two versions will prevent this problem.

**Comment by jira-importer** [comment]
**[Mike Perham](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mperham)** commented

I can't upgrade xdoclet to use antrun 1.1 because AbstractAntMojo in 1.1 has the following injected field:

```
/**
 * The plugin dependencies.
 *
 * @parameter expression="${plugin.artifacts}"
 * @required
 * @readonly
 */
private List artifacts;
```

When you subclass this class (as the xdoclet plugin does), it appears that Maven is NOT injecting this field and so `artifacts` is null at runtime.  If we can fix this, we could essentially get rid of the xdoclet plugin and just use antrun directly.

**Comment by jira-importer** [comment]
**[Lee Webb](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=lwebb_c2p)** commented

Any movement on this?

Being unable to use ver 1.1 is preventing me from testing whether MANTRUN-28 resolves maven.test.classpath issues that I am experiencing within my build.

**Comment by jira-importer** [comment]
**[Eirik Bjornset](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eirikbjornset)** commented

I just encountered the same issue and found that I could get around it by entering a dummy ant-run-plugin \<plugin> element with version 1.1 in the master pom .e.g 			
\<build>
\<plugins>
\<plugin>
\<groupId>org.apache.maven.plugins\</groupId>
\<artifactId>maven-antrun-plugin\</artifactId>
\<version>1.1\</version>
\</plugin>

\

    	</plugins>
    </build>

**Comment by jira-importer** [comment]
**[Deepak Gupta](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=clown_monster)** commented

I'm having the same issue as Lee Webb.

I can use version 1.0 of the plugin, to get rid of the exception "Internal error in the plugin manager executing goal 'org.apache.maven.plugins:maven-antrun-plugin:1.1:run ...'", however when I try to use "\<path refid="maven.test.classpath" />" the classpath does not include required classes.

Any idea when a fix will be available ?

thanks,

**Comment by jira-importer** [comment]
**[Subhash Chandran](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=subwiz)** commented

I also faced this issue. I had upgraded Maven from 2.0.4 to 2.0.9, and this issue cropped up. I did a cleanup of the repository:

$ cd ~/.m2/repository/
$ rm -rf   ant/   org/apache/maven/plugins/

After doing this, all the dependencies were automatically updated and the problem was solved!

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

Looking at the trail here, it seems very unlikely that this is/was an antrun problem rather than a maven issue, or even a repository with its nose out of joint.
