### ISSUE TITLE
[MANTRUN-26] antrun unable to use correct attribute values?

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#208]
**[Rik Graetke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=graetrk)** opened **[MANTRUN-26](https://issues.apache.org/jira/browse/MANTRUN-26?redirect=false)** and commented

I tried to "antrun" the following small rmic-task.
Be sure: the rmic.exe is exactly at the location, i'm using here ;-)

    <rmic base="${basedir}/sources"
         classname = "mcbs.aserver.McRemoteServer"
         classpath="${project.compileClasspathElements}"
         compiler="C:/releasebuild/jdk1.5.0_03/bin/rmic.exe">
    </rmic>

Trying this ends up in the following output:

******************************************************************************************************************************************

[DEBUG] Configuring mojo 'org.apache.maven.plugins:maven-antrun-plugin:1.0:run' -->
[DEBUG]   (f) project = org.apache.maven.project.MavenProject@cfe92499
[DEBUG]   (f) tasks =
[DEBUG]   - end configuration --
[INFO] [antrun:run {execution: rmi_compile}]
[INFO] Executing tasks
[DEBUG] getProperty(ns=null, name=ant.reuse.loader, user=false)
[DEBUG] getProperty(ns=null, name=rmic.comp, user=false)
[DEBUG] getProperty(ns=null, name=build.rmic, user=false)
[INFO] ----------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ----------------------------------------------------------------------------
[INFO] Error executing ant tasks

Embedded error: C:/releasebuild/jdk1.5.0_03/bin/rmic.exe can't be found.
[INFO] ----------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error executing ant tasks
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:544)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:469)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:448)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:301)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:268)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:137)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:316)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:113)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:249)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error executing ant tasks
at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:77)
at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:72)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:399)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:519)
... 16 more
Caused by: C:/releasebuild/jdk1.5.0_03/bin/rmic.exe can't be found.
at org.apache.tools.ant.taskdefs.rmic.RmicAdapterFactory.resolveClassName(RmicAdapterFactory.java:79)
at org.apache.tools.ant.taskdefs.rmic.RmicAdapterFactory.getRmic(RmicAdapterFactory.java:61)
at org.apache.tools.ant.taskdefs.Rmic.execute(Rmic.java:498)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:275)
at org.apache.tools.ant.Task.perform(Task.java:364)
at org.apache.tools.ant.Target.execute(Target.java:341)
at org.apache.maven.plugin.antrun.AbstractAntMojo.executeTasks(AbstractAntMojo.java:71)
... 19 more
Caused by: java.lang.ClassNotFoundException: C:/releasebuild/jdk1.5.0_03/bin/rmic.exe
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:164)
at org.apache.tools.ant.taskdefs.rmic.RmicAdapterFactory.resolveClassName(RmicAdapterFactory.java:75)
... 25 more
[INFO] ----------------------------------------------------------------------------
[INFO] Total time: 2 minutes 26 seconds
[INFO] Finished at: Fri Nov 18 13:58:44 CET 2005
[INFO] Final Memory: 10M/154M
[INFO] ----------------------------------------------------------------------------

******************************************************************************************************************************************

I tried Slashes/backslashes, removing ".exe", but nothing works

Runs fine, if executed directly from ant
Other executions of the plugin(simple copy/delete/mkdir-tasks) from the same POM are running fine

---
No further details from [MANTRUN-26](https://issues.apache.org/jira/browse/MANTRUN-26?redirect=false)

**Comment by jira-importer** [comment]
**[Rik Graetke](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=graetrk)** commented

My fault - no error
