### ISSUE TITLE
[MANTRUN-166] An Ant BuildException has occured: Problem: failed to create task or type classpath

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#285]
**[daivish shah](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=daivish)** opened **[MANTRUN-166](https://issues.apache.org/jira/browse/MANTRUN-166?redirect=false)** and commented

Hi,

When i use following line of code, I am getting exception.

\<build>	
		\<plugins>
			\<plugin>
				\<groupId>org.apache.maven.plugins\</groupId>
				\<artifactId>maven-compiler-plugin\</artifactId>
				\<version>2.3.2\</version>
				\<configuration> 
					\<source>1.5\</source>
					\<target>${java-version}\</target> 
				\</configuration>
			\</plugin>
			\<plugin>
				\<groupId>org.apache.maven.plugins\</groupId>
				\<artifactId>maven-antrun-plugin\</artifactId>
				\<version>1.6\</version>
				\<executions>
					\<execution>
						\<id>install\</id>
						\<phase>install\</phase>
						\<goals>
							\<goal>run\</goal>
						\</goals>
						\<configuration>
							\<tasks>
						    \<classpath refid="maven.dependency.classpath"/>
						    \<ant antfile="build.xml" />
						    \</tasks>
						\</configuration>
					\</execution>
				\</executions>
				\<dependencies>
\<dependency>
\<groupId>crimson\</groupId>
\<artifactId>crimson\</artifactId>
\<version>1.1.3\</version>
\</dependency>
				\</dependencies>
			\</plugin>
		\</plugins>
	\</build>

Exception Details.

[INFO] Executing tasks

main:
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An Ant BuildException has occured: Problem: failed to create task or type classpath
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any \<presetdef>/\<macrodef> declarations have taken place.

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Tue Aug 09 15:26:23 PDT 2011
[INFO] Final Memory: 12M/21M
[INFO] ------------------------------------------------------------------------

And if i commented out \ means

    <build>	
    	<plugins>
    		<plugin>
    			<groupId>org.apache.maven.plugins</groupId>
    			<artifactId>maven-compiler-plugin</artifactId>
    			<version>2.3.2</version>
    			<configuration> 
    				<source>1.5</source>
    				<target>${java-version}</target> 
    			</configuration>
    		</plugin>
    		<plugin>
    			<groupId>org.apache.maven.plugins</groupId>
    			<artifactId>maven-antrun-plugin</artifactId>
    			<version>1.6</version>
    			<executions>
    				<execution>
    					<id>install</id>
    					<phase>install</phase>
    					<goals>
    						<goal>run</goal>
    					</goals>
    					<configuration>
    						<tasks>
    						  
    					    <ant antfile="build.xml" />
    					    </tasks>
    					</configuration>
    				</execution>
    			</executions>
    			<dependencies>

\<dependency>
\<groupId>crimson\</groupId>
\<artifactId>crimson\</artifactId>
\<version>1.1.3\</version>
\</dependency>
				\</dependencies>
			\</plugin>
		\</plugins>
	\</build>

I am getting following type of error.

[wlwBuild]     \<server-classpath> :
[wlwBuild]         C:/bea/weblogic81/../jdk142_04/jre/lib/rt.jar
[wlwBuild]         C:/bea/weblogic81/../jdk142_04/jre/lib/jsse.jar
[wlwBuild]         C:/bea/weblogic81/../jdk142_04/jre/lib/jce.jar
[wlwBuild]         C:/bea/weblogic81/../jdk142_04/lib/tools.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/knex.jar
[wlwBuild]         C:/bea/weblogic81/common/lib/log4j.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/debugging.jar
[wlwBuild]         C:/bea/weblogic81/javelin/lib/javelin.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/wlw-lang.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/weblogic.jar
[wlwBuild]         C:/bea/weblogic81/common/eval/pointbase/lib/pbserver44.jar
[wlwBuild]         C:/bea/weblogic81/common/eval/pointbase/lib/pbclient44.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/webservices.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/webserviceclient.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/webserviceclient+ssl.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/wli.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/xbean.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/wlxbean.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/xqrl.jar
[wlwBuild]         C:/bea/weblogic81/server/lib/netui/netui-compiler.jar

[wlwBuild]     \<output-filename> : WPSSchemas.jar
[wlwBuild] [Build] Build project WPSSchemas started.
[wlwBuild] [Build] BUILD STARTED
[wlwBuild] [Build] build:
[wlwBuild] [Build] check-uptodate:
[wlwBuild] [Build] Skipping source compilation.  C:\CARR/WPSSchemas.jar is up to date.
[wlwBuild] [Build] build-sub:
[wlwBuild] [Build] build-channel-manifest:
[wlwBuild] [Build] BUILD SUCCESSFUL
[wlwBuild] [Build] Build project WPSSchemas complete.
[wlwBuild] java.lang.reflect.InvocationTargetException
[wlwBuild] java.lang.reflect.InvocationTargetException
[wlwBuild] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[wlwBuild] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[wlwBuild] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[wlwBuild] 	at java.lang.reflect.Method.invoke(Method.java:592)
[wlwBuild] 	at workshop.core.Compile.start(Compile.java:19)
[wlwBuild] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[wlwBuild] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[wlwBuild] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[wlwBuild] 	at java.lang.reflect.Method.invoke(Method.java:592)
[wlwBuild] 	at workshop.core.Starter.invokeStart(Starter.java:34)
[wlwBuild] 	at workshop.core.Compile.main(Compile.java:9)
[wlwBuild] Caused by: java.lang.NoClassDefFoundError: org/apache/crimson/tree/XmlDocument
[wlwBuild] 	at workshop.util.ide.PreferencesNode._export(PreferencesNode.java:540)
[wlwBuild] 	at workshop.util.ide.PreferencesNode.exportSubtree(PreferencesNode.java:820)
[wlwBuild] 	at workshop.util.ide.PreferencesNode.flush(PreferencesNode.java:984)
[wlwBuild] 	at workshop.core.App$15.run(App.java:1000)
[wlwBuild] 	at workshop.core.asynctask.AsyncTaskManager.showDialogWhileRunning(AsyncTaskManager.java:272)
[wlwBuild] 	at workshop.core.asynctask.AsyncTaskManager.showDialogWhileRunning(AsyncTaskManager.java:482)
[wlwBuild] 	at workshop.core.App.exit(App.java:994)
[wlwBuild] 	at workshop.core.CompileHelper.compile(CompileHelper.java:300)
[wlwBuild] 	... 11 more
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] An Ant BuildException has occured: The following error occurred while executing this line:
C:WPS\build.xml:68: Java returned: -1

Please let me know, Where i am wrong ?

---

**Affects:** 1.6

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

This looks to me to be a support request, not a bug report. I'd guess that your build.xml uses tasks that aren't included in the standard plugin classpath, in which case you'd need to add dependencies.
