### ISSUE TITLE
[MANTRUN-200] Scriptdef tasks fail to load when running on Java9

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-antrun-plugin#308]
**[Dan Berindei](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.berindei)** opened **[MANTRUN-200](https://issues.apache.org/jira/browse/MANTRUN-200?redirect=false)** and commented

I have a Maven project using maven-antrun-plugin:

```
<?xml version='1.0' encoding='UTF-8'?>
<project>
   <modelVersion>4.0.0</modelVersion>
   <artifactId>my-test-app</artifactId>
   <groupId>my-test-group</groupId>
   <version>1.0-SNAPSHOT</version>

   <build>
      <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-antrun-plugin</artifactId>
            <version>1.8</version>
            <executions>
               <execution>
                  <id>compile</id>
                  <phase>compile</phase>
                  <configuration>
                     <target>
                        <ant antfile="build.xml" inheritRefs="true">
                           <target name="all"/>
                        </ant>
                     </target>
                  </configuration>
                  <goals>
                     <goal>run</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
      </plugins>
   </build>
</project>
```

The Ant build file uses a script:

```
<?xml version='1.0' encoding='UTF-8'?>
<project name="scriptdef-test-build">
   <scriptdef name="test-script" language="javascript">
      <![CDATA[
           var System = Java.type('java.lang.System');
           System.out.println("Working!");
        ]]>
   </scriptdef>
   <target name="all">
      <test-script/>
   </target>
</project>
```

On Java 8 it works, but on Java 9 (9-ea+162) it can't find the script engine:

```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (compile) on project my-test-app: An Ant BuildException has occured: The following error occurred while executing this line:
/home/dan/scriptdef-test/build.xml:10: Unable to create javax script engine for javascript
around Ant part ...<ant antfile="build.xml" inheritRefs="true">... @ 4:47 in /home/dan/scriptdef-test/target/antrun/build-main.xml
...    
Caused by: /home/dan/scriptdef-test/build.xml:10: Unable to create javax script engine for javascript
    at org.apache.tools.ant.util.optional.JavaxScriptRunner.evaluateScript(JavaxScriptRunner.java:84)
    at org.apache.tools.ant.util.optional.JavaxScriptRunner.executeScript(JavaxScriptRunner.java:67)
    at org.apache.tools.ant.taskdefs.optional.script.ScriptDef.executeScript(ScriptDef.java:350)
    at org.apache.tools.ant.taskdefs.optional.script.ScriptDefBase.execute(ScriptDefBase.java:50)
    at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:547)
    at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    at org.apache.tools.ant.Task.perform(Task.java:348)
    at org.apache.tools.ant.Target.execute(Target.java:435)
    at org.apache.tools.ant.Target.performTasks(Target.java:456)
    at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
    at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
    at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    ... 34 more
```

I have attached a debugger and I saw that the `ScriptEngineManager` used by `JavaxScriptRunner` doesn't have any script engines, because the service loader it uses doesn't find any `ScriptEngineFactory` implementations. I have tried `\--add-modules jdk.scripting.nashorn` and `\--add-opens jdk.scripting.nashorn/jdk.nashorn.api.scripting=ALL-UNNAMED`, but neither helped.

---

**Affects:** 1.8

**Issue Links:**
- [MNG-6275](https://issues.apache.org/jira/browse/MNG-6275) ServiceLoaderFactory can't find implementations via ClassRealm

0 votes, 5 watchers

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

This can be reproduced for any plugin, not just the Antrun Plugin, so this may be a Maven core concern. In any Mojo, doing

```java
ServiceLoader.load(ScriptEngineFactory.class, classLoader).iterator().hasNext();
```

returns `false` when the `classLoader` used is the plugin class loader, obtained with `getClass().getClassLoader()`. It is the same result of `false` when using thread class loader.

However, when using the system class loader with `ClassLoader.getSystemClassLoader()`, this call correctly returns `true`, which is strange because the plugin class loader should have the system class loader as parent.

**Comment by jira-importer** [comment]
**[Robert Munteanu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rombert)** commented

Maybe someone from the Maven core team can comment? [Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)?

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

All analysis looks correct to me. The `ScriptRunner.generateClassLoader()`  gets the `ClassRealm` from Maven, and I can see that its parentClassLoader is an instance of `ClassLoaders.AppClassLoader`. I need to verify first if the ClassRealm implementation has an issue, otherwise I'll have ask some Java 9  developers for advice.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Maybe [igorf](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=igorf) has some ideas. Classworlds looks okay, so we're indeed back to Maven Core. [As described](https://maven.apache.org/guides/mini/guide-maven-classloading.html) there are several layers of ClassLoaders, it looks like some gets lost with the plugin realm.

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) The parent class loader in `ClassRealm` is indeed correct, the issue is related to the new way `ServiceLoader` looks for services in Java 9 modules: it delegates directly to `ClassLoader.getParent()` and this ignores ClassRealm's `parentClassLoader`. This Jira issue was actually the subject of [that previous mail of mine](http://mail-archives.apache.org/mod_mbox/maven-dev/201706.mbox/%3C49a731c4-a3ed-83d5-13a7-b0e8ec845ad6%40apache.org%3E). I haven't got around to work more on this but it'd be great to have insights of Java 9 devs.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I think I found an important part of the issue, see [DefaultClassRealmManager](https://maven.apache.org/ref/3.5.0/maven-core/xref/org/apache/maven/classrealm/DefaultClassRealmManager.html#L123)

```
ClassRealm classRealm = world.newRealm( realmId, null );
```

Creating a realm like this means calling `new URLClassLoader( new URL\[0], null )`

Converting this to a unittest:

```
    @Test
    public void testLoadClass_ServiceLocator() throws Exception
    {
        ServiceLoader<ScriptEngineFactory> sef1 = ServiceLoader.load( ScriptEngineFactory.class );
        
        assertTrue( "ServiceLoader.load( ScriptEngineFactory.class ) failed", sef1.iterator().hasNext() );
        
        ServiceLoader<ScriptEngineFactory> sef2 = ServiceLoader.load( ScriptEngineFactory.class, new URLClassLoader( new URL[0] ) );
        
        assertTrue( "ServiceLoader.load( ScriptEngineFactory.class, new URLClassLoader( new URL[0] ) ) failed", sef2.iterator().hasNext() );

        ServiceLoader<ScriptEngineFactory> sef3 = ServiceLoader.load( ScriptEngineFactory.class, new URLClassLoader( new URL[0], null ) );
        
        assertTrue( "ServiceLoader.load( ScriptEngineFactory.class, new URLClassLoader( new URL[0], null ) ) failed", sef3.iterator().hasNext() );
    }
```

With Java 7 it all succeed, with Java the third one fails.

Not sure if this should be considered as regression or if we need to pass something else ourselves. I'll contact Java 9 devs.

**Comment by jira-importer** [comment]
**[Guillaume Boué](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gboue)** commented

[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte) Yes, the parent used by ServiceLoader to delegate is returned by `getParent()`, and this is `null`. Just considering modules, it means only services present in modules loaded by the bootstrap classloader are found. I think Nashorn is loaded with the system classloader in Java 9 (and was previously loaded with bootstrap classloader). So from what I gathered, passing the system classloader, instead of `null`, in `world.newRealm( realmId, null )` would solve this Jira issue, meaning the Nashorn implementation would be found (I tested this previously and it really solves it).

But I'm afraid it would just hide another issue: a module loaded by the Maven core extension classloader still would not be found. For that, I believe you would need to pass Core Ext classloader as parent in `world.newRealm( realmId, null )`, or even pass whatever `parent` was passed to `createRealm` in `DefaultClassRealmManager`, but I tested that this has bad consequences for plugins using the Site Plugin. The problem was that the search for a given class would now delegate to the parent first and then plugin classloader. In the case of the Site Plugin, the parent would be the Site Plugin's realm, and this would mean that it is the classes loaded by maven-site that are found before the ones of the plugin itself...and this quickly turned into version conflicts and ClassNotFoundException when the plugin overrides a dependency...

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

With Classworld it is possible to control the order of ClassLoaders.

Btw, when running the test with Java 8 it fails as well, so it is not J9 specific.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

This requires a fix Maven Core, which is done with MNG-6275.

**Comment by jira-importer** [comment]
**[Cristian Gheorghe Florescu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=myset)** commented

Please try \<scriptdef name="test-script" language="javascript" classpathref="maven.plugin.classpath">.

classpathref="maven.plugin.classpath" works for me.

**Comment by jira-importer** [comment]
**[Dan Berindei](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dan.berindei)** commented

For future reference, this did not work for me:

```xml
<scriptdef name="test-script" language="javascript" classpathref="maven.plugin.classpath">
```

I got

```
[ERROR] /home/dan/Work/scriptdef-test/build.xml:3: Reference maven.plugin.classpath not found.
```

This worked:

```xml
   <scriptdef name="test-javascript" language="javascript" classpath="${plugin_classpath}">
      <![CDATA[
           var System = Java.type('java.lang.System');
           System.out.println("Working!");
        ]]>
   </scriptdef>
   <target name="all">
      <property name="plugin_classpath" refid="maven.plugin.classpath"/>

      <test-javascript/>
   </target>
```
